### ISSUE TITLE
PHP 7 .1 dependancy issue with composer.json default PHP version

### ISSUE THREAD

**Issue by john-henry** [experience/smartdown.craft-plugin#11]
When installing your plugin from the new store I ran into an error.

I'm running MAMP with PHP 7.1+ so meet your requirements but because in the root composer.json the config has php 7.0 by default, the installation will fail.

```
"config": {
    "optimize-autoloader": true,
    "platform": {
      "php": "7.0"
    }
  },
```

I just changed to  `"php": "7.1.0"` which got me installed

**Comment by monooso** [comment]
@john-henry Sorry, I completely missed this notification. I'll update the requirement to be more forgiving.

**Comment by monooso** [comment]
@john-henry I finally got around to looking at this, and realised that I have no idea where you're seeing this code:

```
"config": {
  "optimize-autoloader": true,
  "platform": {
    "php": "7.0"
  }
},
```

I've checked [the `composer.json` file](https://github.com/experience/smartdown.craft-plugin/blob/master/composer.json), and it's nowhere to be found. Same goes for [the `composer.lock` file](https://github.com/experience/smartdown.craft-plugin/blob/master/composer.lock).

Am I missing something obvious in your bug report?

**Comment by john-henry** [comment]
@monooso When I said root composer file I meant root of craft install not your plugin. Apologies

**Comment by monooso** [comment]
@john-henry Ohh, right. Thanks for the clarification.
