### ISSUE TITLE
Update for Craft 3

### ISSUE THREAD

**Issue by thomaswinterstetter** [experience/smartdown.craft-plugin#5]
Hello experience,
will you make this available for Craft3 soon?
Thanks!

**Comment by monooso** [comment]
@thomaswinterstetter Thanks for the reminder. I'll schedule some time to get this done before Craft 3 launches.

**Comment by thomaswinterstetter** [comment]
Stephen, thank you. I wouldn't know what to do without your work!

**Comment by thomaswinterstetter** [comment]
Stephen:
big thank you!

--
Thomas Winterstetter
Trierer Str. 57
54329 Konz
Germany
+49-174-6551981
https://winterstetter.online
